# Generated by Django 6.0.2 on 2026-04-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donorprofile_latitude_donorprofile_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='available',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donorprofile'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrganPledge',
        ),
    ]
