# Generated by Django 6.0.3 on 2026-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
