# Generated by Django 6.0.2 on 2026-04-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospitalprofile_latitude_hospitalprofile_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='verified',
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
