# Generated by Django 6.0.3 on 2026-03-30 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_bloodrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas'), ('Corneas', 'Corneas')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
